### ISSUE TITLE
Documentation needs template usage guidance

### ISSUE THREAD

**Issue by sethlivingston** [2degrees/django-recaptcha-field#2]
Consider adding documentation for using the field in a form:

```
    ...
    {{ form.recaptcha | safe }}
    {{ form.recaptcha.errors }}
    ...
```

**Comment by euangoddard** [comment]
I would be happy to do this, but we're not doing anything here that isn't in the main Django documentation. Perhaps a link to that would be useful for people unfamiliar with Django templating engine would be useful?

**Comment by sethlivingston** [comment]
Well with that logic you shouldn't need to document the validation in the view either, right? Also, most fields don't require the `| safe` filter to work properly. IMHO, it's a worthwhile mention.

**Comment by euangoddard** [comment]
That's certainly a fair point. I want to get the balance right between repeating what the Django docs say (and keeping them up-to-date) and making sure everything is understandable. When I get a chance I'll have a look over. If you want to submit a pull request with the bits you feel are lacking that would certainly get things done even quicker.
